global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['web:5000']

